/**
 * finalizeRun against the seven oracle fixtures.
 *
 * The fixtures are generated by the reference PL/pgSQL running in PGlite, so a
 * difference here is a defect in finalizeRun, not a disagreement about what
 * the numbers should be. Rates compare at 4 decimals and ranks at 2; counts
 * and null-ness compare exactly.
 */
import { readFileSync } from "node:fs";
import { beforeEach, afterEach, describe, expect, it } from "vitest";
import { openDatabase, type Driver } from "../db/driver";
import { migrate } from "../db/migrate";
import { seedModels } from "../db/seed-models";
import type { RunMetricRow, RunRow } from "../db/types";
import { finalizeRun } from "./finalize-run";
import {
  fixtureProjectId,
  fixtureRunId,
  loadFixture,
  type Fixture,
  type FixtureMetric,
  type FixtureRunExpectation,
} from "./load-fixture";

const FIXTURE_NAMES = [
  "absent-brand",
  "counting-rule",
  "mixed-failure",
  "perception-excluded",
  "repeat-finalize-idempotent",
  "top3-rate",
  "two-models-with-merged-scope",
] as const;

function readFixture(name: string): Fixture {
  const url = new URL(`./__fixtures__/finalize-run/${name}.json`, import.meta.url);
  return JSON.parse(readFileSync(url, "utf8")) as Fixture;
}

/** The key the oracle row and the stored row are matched on. */
function metricKey(modelId: string | null, promptId: string | null, brandId: string): string {
  return `${modelId ?? "*"}|${promptId ?? "*"}|${brandId}`;
}

function storedMetrics(db: Driver, runId: string): Map<string, RunMetricRow> {
  const rows = db.prepare("SELECT * FROM run_metrics WHERE run_id = ?").all<RunMetricRow>(runId);
  return new Map(
    rows.map((row) => [metricKey(row.model_id, row.prompt_id, row.brand_id ?? ""), row]),
  );
}

function readRun(db: Driver, runId: string): RunRow {
  const row = db.prepare("SELECT * FROM runs WHERE id = ?").get<RunRow>(runId);
  if (!row) throw new Error(`no run ${runId}`);
  return row;
}

function expectRun(run: RunRow, expected: FixtureRunExpectation): void {
  expect(run.status).toBe(expected.status);
  expect(run.planned_calls).toBe(expected.planned_calls);
  expect(run.completed_calls).toBe(expected.completed_calls);
  expect(run.failed_calls).toBe(expected.failed_calls);
  expect(run.started_at !== null).toBe(expected.started_at_set);
  expect(run.finished_at !== null).toBe(expected.finished_at_set);
}

/** A fixture rate is a fixed-scale numeric string, or null. */
function num(value: string | null): number | null {
  return value === null ? null : Number(value);
}

function expectMetric(actual: RunMetricRow | undefined, expected: FixtureMetric): void {
  expect(actual, `missing row for ${expected.scope} ${expected.brand_id}`).toBeDefined();
  if (!actual) return;

  expect(actual.answers).toBe(expected.answers);
  expect(actual.mentions).toBe(expected.mentions);
  expect(actual.ranked).toBe(expected.ranked);
  expect(actual.citations).toBe(expected.citations);
  expect(actual.best_rank).toBe(expected.best_rank);
  expect(actual.worst_rank).toBe(expected.worst_rank);

  const rates: [number | null, number | null][] = [
    [actual.mention_rate, num(expected.mention_rate)],
    [actual.rank_rate, num(expected.rank_rate)],
    [actual.citation_rate, num(expected.citation_rate)],
    [actual.link_when_mentioned, num(expected.link_when_mentioned)],
    [actual.share_of_voice, num(expected.share_of_voice)],
    [actual.top_pick_share, num(expected.top_pick_share)],
    [actual.top3_rate, num(expected.top3_rate)],
  ];
  for (const [got, want] of rates) {
    if (want === null) expect(got).toBeNull();
    else expect(got).toBeCloseTo(want, 4);
  }

  const ranks: [number | null, number | null][] = [
    [actual.avg_rank, num(expected.avg_rank)],
    [actual.rank_stddev, num(expected.rank_stddev)],
  ];
  for (const [got, want] of ranks) {
    if (want === null) expect(got).toBeNull();
    else expect(got).toBeCloseTo(want, 2);
  }
}

let db: Driver;

beforeEach(() => {
  db = openDatabase(":memory:");
  migrate(db);
  seedModels(db);
});

afterEach(() => {
  db.close();
});

describe.each(FIXTURE_NAMES)("finalizeRun fixture %s", (name) => {
  it("writes the run counters and the run_metrics rows the oracle recorded", () => {
    const fixture = readFixture(name);
    loadFixture(db, fixture);
    const runId = fixtureRunId(fixture);

    const summary = finalizeRun(db, runId);

    expect(summary.runId).toBe(runId);
    expect(summary.metricRows).toBe(fixture.expected.run_metrics_row_count);
    expectRun(readRun(db, runId), fixture.expected.run);

    const stored = storedMetrics(db, runId);
    expect(stored.size).toBe(fixture.expected.run_metrics_row_count);
    for (const expected of fixture.expected.run_metrics) {
      expectMetric(
        stored.get(metricKey(expected.model_id, expected.prompt_id, expected.brand_id)),
        expected,
      );
    }

    for (const brandId of fixture.expected.brand_ids_expected_to_have_no_rows ?? []) {
      const rows = db
        .prepare("SELECT count(*) AS n FROM run_metrics WHERE run_id = ? AND brand_id = ?")
        .get<{ n: number }>(runId, brandId);
      expect(rows?.n).toBe(0);
    }
  });

  it("writes identical rows when it is run twice", () => {
    const fixture = readFixture(name);
    loadFixture(db, fixture);
    const runId = fixtureRunId(fixture);

    finalizeRun(db, runId);
    const first = [...storedMetrics(db, runId)].map(([key, row]) => [key, strip(row)] as const);

    const second = finalizeRun(db, runId);
    const after = [...storedMetrics(db, runId)].map(([key, row]) => [key, strip(row)] as const);

    expect(second.metricRows).toBe(fixture.expected.run_metrics_row_count);
    expect(sorted(after)).toEqual(sorted(first));
    expectRun(readRun(db, runId), fixture.expected.run);
  });
});

/** Everything but the freshly generated id and timestamp, which must not match. */
function strip(row: RunMetricRow): Omit<RunMetricRow, "id" | "created_at"> {
  const { id: _id, created_at: _createdAt, ...rest } = row;
  return rest;
}

function sorted(rows: readonly (readonly [string, unknown])[]): readonly unknown[] {
  return [...rows].sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));
}

describe("finalizeRun, the rules the fixtures single out", () => {
  it("refuses an observation written against a perception task", () => {
    const fixture = readFixture("perception-excluded");
    loadFixture(db, fixture);
    const perception = db
      .prepare("SELECT id, run_id, project_id FROM run_tasks WHERE is_perception = 1 LIMIT 1")
      .get<{ id: string; run_id: string; project_id: string }>();
    expect(perception).toBeDefined();

    const insert = (): void => {
      db.prepare(
        `INSERT INTO brand_observations
           (id, run_task_id, run_id, project_id, brand_id, raw_name, mention_type)
         VALUES ('bad', ?, ?, ?, NULL, 'Acme Analytics', 'mentioned')`,
      ).run(perception!.id, perception!.run_id, perception!.project_id);
    };

    expect(insert).toThrow(/PERCEPTION_HAS_NO_OBSERVATIONS/);
  });

  it("still writes every metric row while a perception task is extracting", () => {
    const fixture = readFixture("perception-excluded");
    const expected = fixture.expected.while_perception_still_extracting;
    expect(expected).toBeDefined();
    loadFixture(db, fixture);
    const runId = fixtureRunId(fixture);

    db.prepare("UPDATE run_tasks SET status = 'extracting' WHERE is_perception = 1").run();
    const summary = finalizeRun(db, runId);

    expect(summary.metricRows).toBe(expected!.run_metrics_row_count);
    expectRun(readRun(db, runId), expected!.run);
  });

  it("counts one mention per answer per brand however often the brand is named", () => {
    const fixture = readFixture("counting-rule");
    loadFixture(db, fixture);
    const runId = fixtureRunId(fixture);
    finalizeRun(db, runId);

    const observations = db
      .prepare(
        `SELECT count(*) AS n FROM brand_observations o
           JOIN run_tasks t ON t.id = o.run_task_id
          WHERE t.run_id = ? AND o.brand_id IS NOT NULL`,
      )
      .get<{ n: number }>(runId);
    const aggregate = db
      .prepare("SELECT sum(mentions) AS n FROM run_metrics WHERE run_id = ? AND model_id IS NULL")
      .get<{ n: number }>(runId);

    // A brand named twice in one answer is one mention, so observations
    // outnumber mentions in this fixture.
    expect(observations?.n ?? 0).toBeGreaterThan(aggregate?.n ?? 0);
  });

  it("keeps every metric row inside the project that owns the run", () => {
    const fixture = readFixture("repeat-finalize-idempotent");
    loadFixture(db, fixture);
    const runId = fixtureRunId(fixture);
    finalizeRun(db, runId);

    const rows = db
      .prepare("SELECT DISTINCT project_id FROM run_metrics WHERE run_id = ?")
      .all<{ project_id: string }>(runId);
    expect(rows).toEqual([{ project_id: fixtureProjectId(fixture) }]);
  });

  it("dates every metric row with its run, however long after the run it is scored", () => {
    const fixture = readFixture("repeat-finalize-idempotent");
    loadFixture(db, fixture);
    const runId = fixtureRunId(fixture);
    db.prepare("UPDATE runs SET created_at = '2026-07-01T09:00:00.000Z' WHERE id = ?").run(runId);

    finalizeRun(db, runId);
    finalizeRun(db, runId);

    const dates = db
      .prepare("SELECT DISTINCT created_at FROM run_metrics WHERE run_id = ?")
      .all<{ created_at: string }>(runId);
    expect(dates).toEqual([{ created_at: "2026-07-01T09:00:00.000Z" }]);
    expect(readRun(db, runId).finalised_at! > "2026-07-01T09:00:00.000Z").toBe(true);
  });
});
