/**
 * Loading a finalize-run oracle fixture into a SQLite database.
 *
 * The fixtures under __fixtures__/finalize-run are generated by the reference
 * PL/pgSQL under PGlite, so they carry its column names and status vocabulary.
 * This module translates three things and nothing else:
 *
 *   models.model_key / label   become model_id / display_name
 *   models.provider "example"  becomes a real catalogue provider, because the
 *                              models CHECK does not list it and the provider
 *                              name never reaches finalisation
 *   run_tasks.status "blocked" becomes "failed", which this schema has instead
 *                              (ADR 0004). Both count 2 into failed_calls and
 *                              both push the run to partial
 *
 * Everything else is inserted as it is.
 */
import type { Driver } from "../db/driver";
import type { SqlBool } from "../db/types";

/** The provider the fixtures invented. It exists nowhere in the catalogue. */
const FIXTURE_PROVIDER = "example";
const SUBSTITUTE_PROVIDER = "openai";

export interface FixtureMetric {
  scope: string;
  model_id: string | null;
  prompt_id: string | null;
  brand_id: string;
  answers: number;
  mentions: number;
  ranked: number;
  citations: number;
  mention_rate: string;
  rank_rate: string;
  citation_rate: string;
  link_when_mentioned: string | null;
  avg_rank: string | null;
  best_rank: number | null;
  worst_rank: number | null;
  rank_stddev: string | null;
  share_of_voice: string | null;
  top_pick_share: string | null;
  top3_rate: string | null;
}

export interface FixtureRunExpectation {
  status: string;
  planned_calls: number;
  completed_calls: number;
  failed_calls: number;
  started_at_set: boolean;
  finished_at_set: boolean;
}

export interface Fixture {
  name: string;
  description: string;
  input: {
    projects: { id: string; name: string }[];
    models: {
      id: string;
      provider: string;
      model_key: string;
      label: string;
      tier: string;
    }[];
    prompts: {
      id: string;
      project_id: string;
      text: string;
      category: string | null;
      iterations: number;
    }[];
    brands: { id: string; project_id: string; name: string; role: string }[];
    runs: {
      id: string;
      project_id: string;
      trigger: string;
      status: string;
      planned_calls: number;
      completed_calls: number;
      failed_calls: number;
      config_snapshot: string;
    }[];
    run_tasks: {
      id: string;
      run_id: string;
      project_id: string;
      prompt_id: string | null;
      model_id: string;
      iteration: number;
      question_text: string | null;
      is_perception: boolean;
      status: string;
      attempts: number;
      answer_text: string | null;
      error: string | null;
    }[];
    brand_observations: {
      id: string;
      run_task_id: string;
      run_id: string;
      project_id: string;
      brand_id: string | null;
      raw_name: string;
      position: number | null;
      total_items: number | null;
      mention_type: string;
      linked_url: string | null;
      is_cited: boolean;
      evidence: string | null;
    }[];
  };
  expected: {
    run: FixtureRunExpectation;
    run_metrics_row_count: number;
    second_finalize_identical: boolean;
    run_metrics: FixtureMetric[];
    brand_ids_expected_to_have_no_rows?: string[];
    perception_observation_insert_raises?: boolean;
    perception_observation_error_prefix?: string;
    while_perception_still_extracting?: {
      run: FixtureRunExpectation;
      run_metrics_row_count: number;
    };
  };
}

function bool(value: boolean): SqlBool {
  return value ? 1 : 0;
}

/** Maps the fixtures' `blocked` status to `failed`. See the module header. */
function taskStatus(status: string): string {
  return status === "blocked" ? "failed" : status;
}

/** The run id every fixture's expectations are about. */
export function fixtureRunId(fixture: Fixture): string {
  const run = fixture.input.runs[0];
  if (!run) throw new Error(`fixture ${fixture.name} has no run`);
  return run.id;
}

/** The project id every fixture's expectations are about. */
export function fixtureProjectId(fixture: Fixture): string {
  const project = fixture.input.projects[0];
  if (!project) throw new Error(`fixture ${fixture.name} has no project`);
  return project.id;
}

/** Inserts every input row. The database must already be migrated. */
export function loadFixture(db: Driver, fixture: Fixture): void {
  const input = fixture.input;

  db.transaction(() => {
    for (const row of input.projects) {
      db.prepare("INSERT INTO projects (id, name) VALUES (?, ?)").run(row.id, row.name);
    }

    for (const row of input.models) {
      db.prepare(
        `INSERT INTO models (id, provider, model_id, display_name, tier)
         VALUES (?, ?, ?, ?, ?)`,
      ).run(
        row.id,
        row.provider === FIXTURE_PROVIDER ? SUBSTITUTE_PROVIDER : row.provider,
        row.model_key,
        row.label,
        row.tier,
      );
    }

    for (const row of input.prompts) {
      db.prepare(
        "INSERT INTO prompts (id, project_id, text, category, iterations) VALUES (?, ?, ?, ?, ?)",
      ).run(row.id, row.project_id, row.text, row.category, row.iterations);
    }

    for (const row of input.brands) {
      db.prepare("INSERT INTO brands (id, project_id, name, role) VALUES (?, ?, ?, ?)").run(
        row.id,
        row.project_id,
        row.name,
        row.role,
      );
    }

    for (const row of input.runs) {
      db.prepare(
        `INSERT INTO runs
           (id, project_id, trigger, status, planned_calls, completed_calls, failed_calls, config_snapshot)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
      ).run(
        row.id,
        row.project_id,
        row.trigger,
        row.status,
        row.planned_calls,
        row.completed_calls,
        row.failed_calls,
        row.config_snapshot,
      );
    }

    for (const row of input.run_tasks) {
      db.prepare(
        `INSERT INTO run_tasks
           (id, run_id, project_id, prompt_id, model_id, iteration, question_text,
            is_perception, status, attempts, answer_text, error)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      ).run(
        row.id,
        row.run_id,
        row.project_id,
        row.prompt_id,
        row.model_id,
        row.iteration,
        row.question_text,
        bool(row.is_perception),
        taskStatus(row.status),
        row.attempts,
        row.answer_text,
        row.error,
      );
    }

    for (const row of input.brand_observations) {
      db.prepare(
        `INSERT INTO brand_observations
           (id, run_task_id, run_id, project_id, brand_id, raw_name, position, total_items,
            mention_type, linked_url, is_cited, evidence)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      ).run(
        row.id,
        row.run_task_id,
        row.run_id,
        row.project_id,
        row.brand_id,
        row.raw_name,
        row.position,
        row.total_items,
        row.mention_type,
        row.linked_url,
        bool(row.is_cited),
        row.evidence,
      );
    }
  });
}
