/**
 * A run's status and counters, derived from its tasks. cancelRun also writes
 * status, and `cancelled` is sticky: a late-arriving answer cannot resurrect a
 * run the user stopped, though the counters and timestamps on a cancelled run
 * are still refreshed.
 *
 * Counters are recomputed from the tasks, never incremented, so a recount is
 * idempotent and cannot drift. The finalize-run fixtures, generated by the
 * reference PL/pgSQL, check these counters too.
 */
import type { Driver } from "../db/driver";
import type { RunStatus } from "../db/types";
import type { RunProgress } from "./types";
import { CALLS_PER_ANSWER } from "@/lib/run-progress";

/** Counts over one run's tasks. The p-prefixed ones count perception tasks. */
interface TaskCounts {
  done: number;
  mid: number;
  failed: number;
  pending: number;
  measured: number;
  pDone: number;
  pMid: number;
  pFailed: number;
  /** Pending, split three ways: never asked, waiting on the automatic retry, call in flight. */
  fresh: number;
  retrying: number;
  working: number;
}

const COUNT_SQL = `
  SELECT
    sum(CASE WHEN status = 'done' AND is_perception = 0 THEN 1 ELSE 0 END) AS done,
    sum(CASE WHEN status IN ('answered','extracting') AND is_perception = 0 THEN 1 ELSE 0 END) AS mid,
    sum(CASE WHEN status = 'failed' AND is_perception = 0 THEN 1 ELSE 0 END) AS failed,
    sum(CASE WHEN status NOT IN ('done','failed') THEN 1 ELSE 0 END) AS pending,
    sum(CASE WHEN is_perception = 0 THEN 1 ELSE 0 END) AS measured,
    sum(CASE WHEN is_perception = 1 AND status = 'done' THEN 1 ELSE 0 END) AS p_done,
    sum(CASE WHEN is_perception = 1 AND status IN ('answered','extracting') THEN 1 ELSE 0 END) AS p_mid,
    sum(CASE WHEN is_perception = 1 AND status = 'failed' THEN 1 ELSE 0 END) AS p_failed,
    sum(CASE WHEN status = 'queued' AND attempts = 0 THEN 1 ELSE 0 END) AS fresh,
    sum(CASE WHEN status IN ('queued','answered') AND attempts > 0 THEN 1 ELSE 0 END) AS retrying,
    sum(CASE WHEN status IN ('in_flight','extracting') OR (status = 'answered' AND attempts = 0)
        THEN 1 ELSE 0 END) AS working
  FROM run_tasks WHERE run_id = ?`;

function countTasks(db: Driver, runId: string): TaskCounts {
  const row = db.prepare(COUNT_SQL).get<Record<string, number | null>>(runId);
  const read = (key: string): number => (row ? (row[key] ?? 0) : 0);
  return {
    done: read("done"),
    mid: read("mid"),
    failed: read("failed"),
    pending: read("pending"),
    measured: read("measured"),
    pDone: read("p_done"),
    pMid: read("p_mid"),
    pFailed: read("p_failed"),
    fresh: read("fresh"),
    retrying: read("retrying"),
    working: read("working"),
  };
}

/**
 * A run with no measured tasks is judged on its perception tasks alone;
 * otherwise perception tasks never make a run partial or failed.
 */
function nextStatus(current: RunStatus, c: TaskCounts): RunStatus {
  if (current === "cancelled") return current;
  if (c.pending > 0) return "running";
  if (c.measured === 0) {
    if (c.pDone === 0) return "failed";
    return c.pFailed > 0 ? "partial" : "completed";
  }
  if (c.done === 0) return "failed";
  return c.failed > 0 ? "partial" : "completed";
}

interface RunHeader {
  status: RunStatus;
  planned_calls: number;
  started_at: string | null;
  finished_at: string | null;
}

const HEADER_SQL = "SELECT status, planned_calls, started_at, finished_at FROM runs WHERE id = ?";

/**
 * Recounts the run tasks and returns what the row should say, writing nothing.
 * Screens call this, because a GET must not write: the run page polls on the
 * connection the worker uses, and the loopback gate only guards mutating
 * methods.
 */
export function readRunProgress(db: Driver, runId: string): RunProgress {
  const run = db.prepare(HEADER_SQL).get<RunHeader>(runId);
  if (!run) throw new Error(`RUN_NOT_FOUND: no run ${runId}`);
  return derive(db, runId, run, new Date().toISOString());
}

/**
 * Recounts the run tasks and writes completed_calls, failed_calls, status,
 * started_at and finished_at. Statuses: running while anything is pending,
 * completed when everything is done, partial when some done and some failed,
 * failed when nothing is done. The worker calls this; a read calls
 * readRunProgress.
 */
export function updateRunProgress(db: Driver, runId: string): RunProgress {
  const run = db.prepare(HEADER_SQL).get<RunHeader>(runId);
  if (!run) throw new Error(`RUN_NOT_FOUND: no run ${runId}`);

  const progress = derive(db, runId, run, new Date().toISOString());

  db.prepare(
    `UPDATE runs
        SET completed_calls = ?, failed_calls = ?, status = ?, started_at = ?, finished_at = ?
      WHERE id = ?`,
  ).run(
    progress.completedCalls,
    progress.failedCalls,
    progress.status,
    progress.startedAt,
    progress.finishedAt,
    runId,
  );

  return progress;
}

function derive(db: Driver, runId: string, run: RunHeader, now: string): RunProgress {
  const counts = countTasks(db, runId);
  const perceptionOnly = counts.measured === 0;
  const completedCalls = perceptionOnly
    ? counts.pDone * CALLS_PER_ANSWER + counts.pMid
    : counts.done * CALLS_PER_ANSWER + counts.mid;
  const failedCalls = perceptionOnly
    ? counts.pFailed * CALLS_PER_ANSWER
    : counts.failed * CALLS_PER_ANSWER;

  // The stored finish time wins, like started_at, so a recount of an old run
  // does not move the day it finished.
  const finishedAt = counts.pending === 0 ? (run.finished_at ?? now) : null;

  return {
    runId,
    status: nextStatus(run.status, counts),
    plannedCalls: run.planned_calls,
    completedCalls,
    failedCalls,
    pending: counts.pending,
    fresh: counts.fresh,
    retrying: counts.retrying,
    working: counts.working,
    startedAt: run.started_at ?? now,
    finishedAt,
  };
}
