-- Overheard AI initial schema. One local install, so there is no tenancy, auth
-- or billing (docs/decisions/0004-v1-scope.md).
--
-- Conventions, applied everywhere:
--   ids          TEXT holding a UUID generated by randomUUID() in TypeScript
--   timestamps   TEXT holding ISO-8601 UTC, the shape Date#toISOString writes
--   booleans     INTEGER 0 or 1
--   string lists TEXT holding a JSON array
--   rates        REAL rounded to 4 decimals, ranks to 2, the numeric scales of
--                the PL/pgSQL fixtures, so fixture comparison stays exact
--
-- Tables are STRICT so a wrong type is a loud error rather than a silent
-- coercion. The timestamp defaults exist as a safety net only; every write path
-- supplies its own value.

CREATE TABLE models (
  id                    TEXT PRIMARY KEY,
  provider              TEXT    NOT NULL CHECK (provider IN ('openai','anthropic','google','perplexity','moonshot')),
  model_id              TEXT    NOT NULL,
  display_name          TEXT    NOT NULL,
  tier                  TEXT    NOT NULL DEFAULT 'mid' CHECK (tier IN ('extraction','mid','frontier')),
  supports_web_search   INTEGER NOT NULL DEFAULT 0 CHECK (supports_web_search IN (0,1)),
  input_price_per_mtok  REAL    NOT NULL DEFAULT 0,
  output_price_per_mtok REAL    NOT NULL DEFAULT 0,
  search_price_per_call REAL    NOT NULL DEFAULT 0,
  is_extraction_model   INTEGER NOT NULL DEFAULT 0 CHECK (is_extraction_model IN (0,1)),
  -- Lower is preferred as the extractor. Seeded cheapest first, by published
  -- input price.
  extraction_rank       INTEGER,
  is_active             INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  created_at            TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
) STRICT;

CREATE UNIQUE INDEX models_provider_model_idx ON models (provider, model_id);

CREATE TABLE projects (
  id                  TEXT PRIMARY KEY,
  name                TEXT    NOT NULL,
  extraction_model_id TEXT REFERENCES models(id),
  web_search_enabled  INTEGER NOT NULL DEFAULT 1 CHECK (web_search_enabled IN (0,1)),
  -- A blank prompt is the off switch. There is no separate enabled flag.
  perception_prompt   TEXT    NOT NULL DEFAULT 'What do you know about {brand}?

Please cover, in order: what {brand} does; who its typical customers are, including their size and the industries they work in; what it is well regarded for; and what criticisms, weaknesses or common complaints come up, with specifics rather than generalities.

If you are not familiar with {brand}, say so plainly instead of guessing.',
  created_at          TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at          TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
) STRICT;

CREATE TRIGGER projects_set_updated_at
AFTER UPDATE ON projects
FOR EACH ROW
WHEN NEW.updated_at = OLD.updated_at
BEGIN
  UPDATE projects
     SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
   WHERE id = NEW.id;
END;

-- One table for the target brand and every competitor, told apart by `role`.
-- `discovered` is written by the worker for a brand first seen in an answer and
-- is promoted to `competitor` by the auto-track path.
CREATE TABLE brands (
  id                TEXT PRIMARY KEY,
  project_id        TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name              TEXT    NOT NULL,
  role              TEXT    NOT NULL CHECK (role IN ('target','competitor','discovered')),
  variants          TEXT    NOT NULL DEFAULT '[]',
  domains           TEXT    NOT NULL DEFAULT '[]',
  suggested_domains TEXT    NOT NULL DEFAULT '[]',
  is_active         INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  created_at        TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
) STRICT;

CREATE INDEX brands_project_role_idx ON brands (project_id, role);
CREATE UNIQUE INDEX brands_project_name_idx ON brands (project_id, lower(name));

-- `category` is the user-facing tag. There is no tags table: a second taxonomy
-- under a different name is worse than a badly named column. Null is Untagged.
CREATE TABLE prompts (
  id         TEXT PRIMARY KEY,
  project_id TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  text       TEXT    NOT NULL CHECK (length(text) <= 2000),
  context    TEXT CHECK (context IS NULL OR length(context) <= 8000),
  category   TEXT,
  iterations INTEGER NOT NULL DEFAULT 5 CHECK (iterations BETWEEN 1 AND 100),
  is_active  INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  created_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  CHECK (length(text) + length(coalesce(context,'')) <= 10000)
) STRICT;

CREATE INDEX prompts_project_active_idx ON prompts (project_id) WHERE is_active = 1;

CREATE TRIGGER prompts_set_updated_at
AFTER UPDATE ON prompts
FOR EACH ROW
WHEN NEW.updated_at = OLD.updated_at
BEGIN
  UPDATE prompts
     SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
   WHERE id = NEW.id;
END;

-- The monitored assistant set. This is what a run fans out over.
CREATE TABLE project_models (
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  model_id   TEXT NOT NULL REFERENCES models(id) ON DELETE CASCADE,
  PRIMARY KEY (project_id, model_id)
) STRICT;

CREATE TABLE runs (
  id              TEXT PRIMARY KEY,
  project_id      TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  trigger         TEXT    NOT NULL DEFAULT 'manual' CHECK (trigger IN ('manual','scheduled')),
  status          TEXT    NOT NULL DEFAULT 'queued'
                    CHECK (status IN ('queued','running','completed','partial','failed','cancelled')),
  -- Provider calls, already doubled: one to ask, one to extract.
  planned_calls   INTEGER NOT NULL,
  completed_calls INTEGER NOT NULL DEFAULT 0,
  failed_calls    INTEGER NOT NULL DEFAULT 0,
  config_snapshot TEXT    NOT NULL,
  error           TEXT,
  started_at      TEXT,
  finished_at     TEXT,
  created_at      TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
) STRICT;

CREATE INDEX runs_project_created_idx ON runs (project_id, created_at DESC);

-- One row per answer. The answer text lives here, not in a separate table:
-- retry and claim both depend on reading it off the task row.
CREATE TABLE run_tasks (
  id                TEXT PRIMARY KEY,
  run_id            TEXT    NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
  project_id        TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  -- ON DELETE SET NULL, not CASCADE: a detached task still holds the question
  -- it asked in question_text. The app's prompt delete removes the prompt's
  -- measured tasks itself (see 0004).
  prompt_id         TEXT REFERENCES prompts(id) ON DELETE SET NULL,
  model_id          TEXT    NOT NULL REFERENCES models(id),
  iteration         INTEGER NOT NULL,
  question_text     TEXT,
  is_perception     INTEGER NOT NULL DEFAULT 0 CHECK (is_perception IN (0,1)),
  status            TEXT    NOT NULL DEFAULT 'queued'
                      CHECK (status IN ('queued','in_flight','answered','extracting','done','failed')),
  attempts          INTEGER NOT NULL DEFAULT 0,
  next_attempt_at   TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  locked_at         TEXT,
  locked_by         TEXT,
  answer_text       TEXT,
  answer_tokens     INTEGER,
  latency_ms        INTEGER,
  provider_cost_usd REAL,
  error             TEXT,
  created_at        TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
) STRICT;

-- Nulls are distinct in SQLite, so this does not constrain perception rows.
CREATE UNIQUE INDEX run_tasks_unique_idx ON run_tasks (run_id, prompt_id, model_id, iteration);
CREATE INDEX run_tasks_claimable_idx ON run_tasks (next_attempt_at) WHERE status IN ('queued','answered');
CREATE INDEX run_tasks_run_idx ON run_tasks (run_id);
-- Serves prompt answer counts, and keeps the ON DELETE SET NULL above cheap.
CREATE INDEX run_tasks_prompt_status_idx ON run_tasks (prompt_id, status);

-- One row per scored answer. raw_json is what makes extraction auditable and
-- re-runnable without paying a provider again.
CREATE TABLE extractions (
  id            TEXT PRIMARY KEY,
  run_task_id   TEXT    NOT NULL UNIQUE REFERENCES run_tasks(id) ON DELETE CASCADE,
  project_id    TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  answer_format TEXT    NOT NULL CHECK (answer_format IN ('ranked_list','unranked_list','prose','refusal')),
  total_items   INTEGER,
  raw_json      TEXT    NOT NULL,
  model_used    TEXT    NOT NULL,
  created_at    TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
) STRICT;

-- A citation is is_cited = 1 with the URL in linked_url. There is no citations
-- table and no sentiment column.
CREATE TABLE brand_observations (
  id           TEXT PRIMARY KEY,
  run_task_id  TEXT    NOT NULL REFERENCES run_tasks(id) ON DELETE CASCADE,
  run_id       TEXT    NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
  project_id   TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  -- Null means the raw name resolved to nothing. The row is kept and excluded
  -- from metrics rather than dropped.
  brand_id     TEXT REFERENCES brands(id) ON DELETE SET NULL,
  raw_name     TEXT    NOT NULL,
  position     INTEGER,
  total_items  INTEGER,
  mention_type TEXT    NOT NULL CHECK (mention_type IN ('ranked','recommended','mentioned','negative')),
  linked_url   TEXT,
  is_cited     INTEGER NOT NULL DEFAULT 0 CHECK (is_cited IN (0,1)),
  evidence     TEXT,
  created_at   TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
) STRICT;

CREATE INDEX brand_observations_run_brand_idx ON brand_observations (run_id, brand_id);
CREATE INDEX brand_observations_project_created_idx ON brand_observations (project_id, created_at DESC);

-- A perception answer is read into sections, not mined for brands. Mining one
-- fills a project's competitor list with the brand's own customers, so the
-- insert fails loudly.
CREATE TRIGGER reject_perception_observation
BEFORE INSERT ON brand_observations
FOR EACH ROW
WHEN EXISTS (SELECT 1 FROM run_tasks t WHERE t.id = NEW.run_task_id AND t.is_perception = 1)
BEGIN
  SELECT RAISE(ABORT, 'PERCEPTION_HAS_NO_OBSERVATIONS: a perception answer is read into sections, not mined for brands.');
END;

-- Two scope levels: level 0 is model + prompt, level 1 is null + null, meaning
-- across every assistant and every prompt.
CREATE TABLE run_metrics (
  id                  TEXT PRIMARY KEY,
  run_id              TEXT    NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
  project_id          TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  model_id            TEXT REFERENCES models(id),
  prompt_id           TEXT REFERENCES prompts(id) ON DELETE SET NULL,
  brand_id            TEXT REFERENCES brands(id) ON DELETE CASCADE,
  answers             INTEGER NOT NULL,
  mentions            INTEGER NOT NULL,
  ranked              INTEGER NOT NULL,
  citations           INTEGER NOT NULL,
  mention_rate        REAL    NOT NULL,
  rank_rate           REAL    NOT NULL,
  citation_rate       REAL    NOT NULL,
  link_when_mentioned REAL,
  avg_rank            REAL,
  best_rank           INTEGER,
  worst_rank          INTEGER,
  -- Population standard deviation, so a single sample gives 0.00.
  rank_stddev         REAL,
  share_of_voice      REAL,
  top_pick_share      REAL,
  top3_rate           REAL,
  created_at          TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
) STRICT;

CREATE INDEX run_metrics_project_brand_created_idx ON run_metrics (project_id, brand_id, created_at DESC);
-- Nulls are distinct, so a plain unique constraint would not hold the aggregate
-- rows apart. Coalescing to a sentinel makes a duplicate scope row an error even
-- if finalisation's delete-before-insert is skipped.
CREATE UNIQUE INDEX run_metrics_scope_idx ON run_metrics (
  run_id,
  coalesce(model_id, ''),
  coalesce(prompt_id, ''),
  coalesce(brand_id, '')
);

-- Current state, not history: one row per (project, assistant) plus one merged
-- row with a null model_id, replaced each time the question is asked.
CREATE TABLE perception_summaries (
  id                TEXT PRIMARY KEY,
  project_id        TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  model_id          TEXT REFERENCES models(id) ON DELETE CASCADE,
  run_id            TEXT REFERENCES runs(id) ON DELETE SET NULL,
  -- What tells the interface an answer has gone stale.
  question_text     TEXT,
  -- A column of its own, because an assistant that has never heard of the
  -- brand is a finding, not a detail to bury inside a prose field.
  knows_brand       INTEGER NOT NULL DEFAULT 1 CHECK (knows_brand IN (0,1)),
  what_it_does      TEXT,
  typical_customers TEXT,
  well_regarded_for TEXT,
  downsides         TEXT,
  source_answers    INTEGER NOT NULL DEFAULT 1,
  created_at        TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at        TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
) STRICT;

CREATE UNIQUE INDEX perception_summaries_scope_idx
  ON perception_summaries (project_id, coalesce(model_id, ''));

-- No cron expression. A structured cadence plus a day and an hour, resolved by
-- nextOccurrence(). day_of_month is capped at 28 so a monthly schedule exists in
-- every month. hour_utc holds the local hour in `timezone`, despite its name.
CREATE TABLE schedules (
  id               TEXT PRIMARY KEY,
  project_id       TEXT    NOT NULL UNIQUE REFERENCES projects(id) ON DELETE CASCADE,
  cadence          TEXT    NOT NULL CHECK (cadence IN ('daily','weekly','monthly')),
  day_of_week      INTEGER CHECK (day_of_week IS NULL OR day_of_week BETWEEN 0 AND 6),
  day_of_month     INTEGER CHECK (day_of_month IS NULL OR day_of_month BETWEEN 1 AND 28),
  hour_utc         INTEGER NOT NULL CHECK (hour_utc BETWEEN 0 AND 23),
  timezone         TEXT    NOT NULL DEFAULT 'UTC',
  is_active        INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  next_run_at      TEXT    NOT NULL,
  -- Moves only on success.
  last_run_at      TEXT,
  -- Set by a skip or a failure, cleared by a success.
  last_skip_reason TEXT,
  -- Moves only on a skip or a failure.
  last_skipped_at  TEXT,
  created_at       TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
) STRICT;

CREATE INDEX schedules_next_run_idx ON schedules (next_run_at) WHERE is_active = 1;

-- A local token and cost log. It answers one question on the run screen: what
-- did this cost on your keys. Every price is an estimate and is labelled as one.
CREATE TABLE usage_events (
  id             TEXT PRIMARY KEY,
  run_id         TEXT REFERENCES runs(id) ON DELETE CASCADE,
  run_task_id    TEXT REFERENCES run_tasks(id) ON DELETE CASCADE,
  kind           TEXT    NOT NULL CHECK (kind IN ('answer','extraction')),
  provider       TEXT    NOT NULL,
  -- The provider's own string id, not a models(id) reference, so the log
  -- survives a catalogue row being retired.
  model_id       TEXT    NOT NULL,
  input_tokens   INTEGER NOT NULL DEFAULT 0,
  output_tokens  INTEGER NOT NULL DEFAULT 0,
  search_calls   INTEGER NOT NULL DEFAULT 0,
  cost_usd       REAL    NOT NULL DEFAULT 0,
  cost_estimated INTEGER NOT NULL DEFAULT 1 CHECK (cost_estimated IN (0,1)),
  outcome        TEXT    NOT NULL,
  created_at     TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
) STRICT;

CREATE INDEX usage_events_run_idx ON usage_events (run_id);
